import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Bookmark, Clock3, MapPin, Star, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { budget, money, type Project, type Profile } from '@/lib/marketplace';

async function save(column: 'project_id'|'freelancer_id', id: string) { const {data:{user}} = await supabase.auth.getUser(); if (!user) { toast.error('Sign in to save this item'); return; } const {data} = await supabase.from('saved_items').select('*').eq('user_id',user.id).eq(column,id).maybeSingle(); if(data) { await supabase.from('saved_items').delete().eq('user_id',user.id).eq(column,id); toast.success('Removed from saved'); } else { const {error} = await supabase.from('saved_items').insert(column==='project_id'?{user_id:user.id,project_id:id}:{user_id:user.id,freelancer_id:id}); if(error) { toast.error(error.message); return; } toast.success('Saved for later'); } }
export function ProjectCard({project:p}: {project:Project}) { return <article className="group rounded-md border border-border bg-card p-6 transition-colors hover:border-primary/40"><div className="flex items-start justify-between gap-4"><div className="flex flex-wrap items-center gap-2 text-xs font-semibold text-primary"><span className="rounded-sm bg-primary/10 px-2.5 py-1">{p.category}</span><span className="text-muted-foreground font-normal">· {new Date(p.created_at).toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span></div><Button variant="ghost" size="icon" title="Save project" onClick={()=>save('project_id',p.id)} className="-mr-2 -mt-2 text-muted-foreground"><Bookmark/></Button></div><Link to="/projects/$id" params={{id:p.id}} className="mt-4 block text-xl font-semibold leading-snug group-hover:text-primary">{p.title}</Link><p className="mt-2 text-sm text-muted-foreground">{p.client_name} · {p.location}</p><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-6 text-muted-foreground">{p.description}</p><div className="mt-5 flex flex-wrap gap-2">{p.skills.slice(0,4).map(s=><span key={s} className="rounded-sm bg-secondary px-2.5 py-1 text-xs text-secondary-foreground">{s}</span>)}</div><div className="mt-6 flex items-center justify-between gap-3 border-t border-border pt-5"><div><div className="font-semibold">{budget(p)}</div><div className="mt-1 text-xs text-muted-foreground">{p.budget_type === 'hourly'?'Hourly':'Fixed price'} · {p.experience_level}</div></div><Button variant="outline" size="icon" asChild title="View project"><Link to="/projects/$id" params={{id:p.id}}><ArrowUpRight/></Link></Button></div></article> }
export function FreelancerCard({person:p}: {person:Profile}) { return <article className="group rounded-md border border-border bg-card p-6 transition-colors hover:border-primary/40"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="flex size-14 shrink-0 items-center justify-center overflow-hidden rounded-full bg-secondary text-lg font-semibold text-primary">{p.avatar_url?<img src={p.avatar_url} alt="" className="size-full object-cover"/>:p.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><Link to="/freelancers/$id" params={{id:p.id}} className="font-semibold hover:text-primary">{p.full_name || 'Lancerly freelancer'}</Link><p className="mt-0.5 text-sm text-muted-foreground">{p.headline}</p></div></div><Button variant="ghost" size="icon" title="Save freelancer" onClick={()=>save('freelancer_id',p.id)} className="-mr-2 -mt-2 text-muted-foreground"><Bookmark/></Button></div><p className="mt-5 line-clamp-2 min-h-10 text-sm leading-6 text-muted-foreground">{p.bio || 'Ready to bring fresh thinking and expertise to your next project.'}</p><div className="mt-5 flex flex-wrap gap-2">{p.skills.slice(0,4).map(s=><span key={s} className="rounded-sm bg-secondary px-2.5 py-1 text-xs">{s}</span>)}</div><div className="mt-6 flex items-center justify-between gap-3 border-t border-border pt-5"><div><div className="font-semibold">{money(p.hourly_rate || 0)}<span className="text-xs font-normal text-muted-foreground"> / hr</span></div><div className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="size-3"/>{p.location || 'Remote'} <span className="ml-2 text-positive">● {p.availability}</span></div></div><Button variant="outline" size="icon" asChild title="View profile"><Link to="/freelancers/$id" params={{id:p.id}}><ArrowUpRight/></Link></Button></div></article> }
